apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n-enterprise
  namespace: n8n
  annotations:
    azure.workload.identity/client-id: "<N8N_KV_IDENTITY_CLIENT_ID>"
  labels:
    azure.workload.identity/use: "true"
automountServiceAccountToken: true
